version: '3'

services:
  app:
    build: .
    image: localhost:5000/flask
  production:
    image: localhost:5000/flask:${BUILD_NUMBER}
    command: python hwd.py
    volumes:
    - .:/code
    ports:
    - "81:81"
